# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 699)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("settings/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pth = QtWidgets.QLabel(self.centralwidget)
        self.pth.setGeometry(QtCore.QRect(10, 0, 621, 17))
        self.pth.setObjectName("pth")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 20, 401, 571))
        self.treeView.setObjectName("treeView")
        self.rld = QtWidgets.QPushButton(self.centralwidget)
        self.rld.setGeometry(QtCore.QRect(1060, 610, 89, 25))
        self.rld.setObjectName("rld")
        self.tln = QtWidgets.QLineEdit(self.centralwidget)
        self.tln.setGeometry(QtCore.QRect(90, 610, 781, 25))
        self.tln.setObjectName("tln")
        self.tlbl = QtWidgets.QLabel(self.centralwidget)
        self.tlbl.setGeometry(QtCore.QRect(20, 610, 71, 21))
        self.tlbl.setObjectName("tlbl")
        self.tRn = QtWidgets.QPushButton(self.centralwidget)
        self.tRn.setGeometry(QtCore.QRect(890, 610, 89, 25))
        self.tRn.setObjectName("tRn")
        self.svBtn = QtWidgets.QPushButton(self.centralwidget)
        self.svBtn.setGeometry(QtCore.QRect(1160, 610, 89, 25))
        self.svBtn.setObjectName("svBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1304, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setCheckable(False)
        self.actionOpen.setMenuRole(QtWidgets.QAction.ApplicationSpecificRole)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionreactingFoam = QtWidgets.QAction(MainWindow)
        self.actionreactingFoam.setObjectName("actionreactingFoam")
        self.rPara = QtWidgets.QAction(MainWindow)
        self.rPara.setObjectName("rPara")
        self.actionBlock_Mesh = QtWidgets.QAction(MainWindow)
        self.actionBlock_Mesh.setObjectName("actionBlock_Mesh")
        self.actionDecompose = QtWidgets.QAction(MainWindow)
        self.actionDecompose.setObjectName("actionDecompose")
        self.actionReconstruct = QtWidgets.QAction(MainWindow)
        self.actionReconstruct.setObjectName("actionReconstruct")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.dlt = QtWidgets.QAction(MainWindow)
        self.dlt.setEnabled(True)
        self.dlt.setObjectName("dlt")
        self.cPar = QtWidgets.QAction(MainWindow)
        self.cPar.setObjectName("cPar")
        self.cAl = QtWidgets.QAction(MainWindow)
        self.cAl.setObjectName("cAl")
        self.pv = QtWidgets.QAction(MainWindow)
        self.pv.setObjectName("pv")
        self.rfs = QtWidgets.QAction(MainWindow)
        self.rfs.setObjectName("rfs")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.chMesh = QtWidgets.QAction(MainWindow)
        self.chMesh.setObjectName("chMesh")
        self.intd = QtWidgets.QAction(MainWindow)
        self.intd.setObjectName("intd")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.dlt)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.intd)
        self.menuRun.addAction(self.actionreactingFoam)
        self.menuRun.addAction(self.rPara)
        self.menuRun.addAction(self.pv)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionBlock_Mesh)
        self.menuRun.addAction(self.chMesh)
        self.menuRun.addAction(self.actionDecompose)
        self.menuRun.addAction(self.actionReconstruct)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionSettings)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.cPar)
        self.menuRun.addAction(self.cAl)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JNK OpenFOAM IDE"))
        self.pth.setText(_translate("MainWindow", "Open controlDict file"))
        self.rld.setText(_translate("MainWindow", "Reload"))
        self.tlbl.setText(_translate("MainWindow", "Terminal"))
        self.tRn.setText(_translate("MainWindow", "Run"))
        self.svBtn.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionreactingFoam.setText(_translate("MainWindow", "Solve"))
        self.actionreactingFoam.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.rPara.setText(_translate("MainWindow", "Solve Parallel"))
        self.rPara.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.actionBlock_Mesh.setText(_translate("MainWindow", "Block Mesh"))
        self.actionBlock_Mesh.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionDecompose.setText(_translate("MainWindow", "Decompose"))
        self.actionDecompose.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionReconstruct.setText(_translate("MainWindow", "Reconstruct"))
        self.actionReconstruct.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSettings.setText(_translate("MainWindow", "Configurations"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionNew_File.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.dlt.setText(_translate("MainWindow", "Delete Selected File"))
        self.dlt.setShortcut(_translate("MainWindow", "Del"))
        self.cPar.setText(_translate("MainWindow", "Clean Processor Dir\'s"))
        self.cAl.setText(_translate("MainWindow", "Clean All"))
        self.pv.setText(_translate("MainWindow", "Para View"))
        self.pv.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.rfs.setText(_translate("MainWindow", "Refresh"))
        self.rfs.setShortcut(_translate("MainWindow", "F5"))
        self.actionSave.setText(_translate("MainWindow", "Save Current File"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.chMesh.setText(_translate("MainWindow", "Check Mesh"))
        self.intd.setText(_translate("MainWindow", "Auto Indent"))
        self.intd.setShortcut(_translate("MainWindow", "Ctrl+I"))

